import { Footer } from "@/components/footer"
import { Header as HeaderClient } from "@/components/header"
import { LegalContent } from "@/components/legal-content"
import { createClient as createServerClient } from "@/lib/supabase/server"

async function Header() {
  const supabaseServer = await createServerClient()
  const { data: { user } } = await supabaseServer.auth.getUser()
  return <HeaderClient initialUser={user} />
}

export default async function CopyrightPolicyPage() {
  const copyrightContent = `AI Generation & Copyright Policy

Last Modified: January 2024

1. Scope of Service
This policy applies to all AI-powered creative modules provided by the platform:
1. Video Generation: Powered by veo3.1-landscape (Cinematic) and veo3.1-portial (Mobile/Fast).
2. Image Generation: Text-to-Image (T2I) and Image-to-Image (I2I) modules.
3. Image Restoration: AI-powered Old Photo Restoration and enhancement services.

2. Ownership of Generated Content
Subject to the terms and conditions herein and the underlying licenses provided by our technology partners (including Google):
1. User Ownership: We claim no ownership over the outputs (videos, generated images, or restored photos) created by users. You retain all rights, titles, and interests in the content you generate, provided your inputs do not infringe upon any third-party intellectual property.
2. Platform License: You grant us a limited, worldwide, royalty-free license to host and process your content solely for the purpose of providing and improving the service.

3. Intellectual Property Rights
1. Technology Ownership: All rights to the underlying AI models (veo3.1-landscape and veo3.1-portial) and the platform's proprietary code remain with DanDan AI Limited or its licensors (Google).
2. Input Material: You represent and warrant that you have the right to use any images uploaded for "Image-to-Video", "Image-to-Image", or "Photo Restoration" purposes.

4. Prohibited Usage
Users are strictly prohibited from using the service to:
1. Create deceptive "Deepfakes" or non-consensual synthetic media of real individuals.
2. Generate content that promotes violence, hate speech, or illegal activities.
3. Infringe upon the copyright, trademark, or privacy rights of any third party.

5. Transparency & Attribution
1. AI Labeling: We recommend labeling content generated by our tools as "AI-Generated" or "AI-Enhanced" when shared publicly.
2. Safety Metadata: Outputs may include digital watermarks or metadata in compliance with safety standards to identify AI-originated or AI-modified media.

6. Disclaimer
1. "As-Is" Service: Content is provided without any warranty. The platform is not liable for artistic inconsistencies or historical inaccuracies in AI-restored photos.
2. Liability: DanDan AI Limited shall not be responsible for any legal disputes arising from user-generated content or improper use of the AI modules.`

  return (
    <main className="min-h-screen">
      <Header />
      <LegalContent
        titleKey="footer.aiCopyrightPolicy"
        updatedAt="2026-1-26"
        sections={[
          { titleKey: "", bodyKeys: [copyrightContent] },
        ]}
      />
      <Footer />
    </main>
  )
}